[build]
  base = "apps/website"
  command = "cd ../.. && npm install && cd netlify/functions && npm install && cd ../../apps/website && npm run build"
  publish = "out"
  functions = "../../netlify/functions"
  
# Next.js runtime and environment variables
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  # Tell Netlify that Supabase anon key is safe to be public
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"